before using cache about CI No.1

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -41,43 +41,43 @@ jobs:
         run: npm install
         working-directory: ./judger-backend/judger-api
 
-cd:
-  name: Continuous Deployment
-  needs: ci
-  runs-on: ubuntu-latest
+  cd:
+    name: Continuous Deployment
+    needs: ci
+    runs-on: ubuntu-latest
 
-  steps:
-    # 1. 코드 체크아웃
-    - name: Check out repository
-      uses: actions/checkout@v2
+    steps:
+      # 1. 코드 체크아웃
+      - name: Check out repository
+        uses: actions/checkout@v2
 
-    # 2. 원격 서버 배포
-    - name: SSH Remote Commands
-      uses: appleboy/ssh-action@v0.1.4
-      with:
-        host: ${{ secrets.DEPLOY_HOST }}
-        username: ${{ secrets.DEPLOY_USER }}
-        key: ${{ secrets.DEPLOY_KEY }}
-        port: ${{ secrets.DEPLOY_PORT }}
-        timeout: 40s
-        script: |
-          echo "#START"
-          cd /home/soft1/prod_2022/sw-judger
+      # 2. 원격 서버 배포
+      - name: SSH Remote Commands
+        uses: appleboy/ssh-action@v0.1.4
+        with:
+          host: ${{ secrets.DEPLOY_HOST }}
+          username: ${{ secrets.DEPLOY_USER }}
+          key: ${{ secrets.DEPLOY_KEY }}
+          port: ${{ secrets.DEPLOY_PORT }}
+          timeout: 40s
+          script: |
+            echo "#START"
+            cd /home/soft1/prod_2022/sw-judger
 
-          echo "############# GIT PULL #############"
-          if git pull origin main; then
-            echo "Git pull successful"
-          else
-            echo "Git pull failed!"
-            exit 1
-          fi
+            echo "############# GIT PULL #############"
+            if git pull origin main; then
+              echo "Git pull successful"
+            else
+              echo "Git pull failed!"
+              exit 1
+            fi
 
-          echo "############# DOCKER-COMPOSE DOWN #############"
-          docker-compose -f docker-compose_prod.yml down --remove-orphans || { echo "Failed to stop existing containers"; exit 1; }
+            echo "############# DOCKER-COMPOSE DOWN #############"
+            docker-compose -f docker-compose_prod.yml down --remove-orphans || { echo "Failed to stop existing containers"; exit 1; }
 
-          echo "############# DOCKER SYSTEM AND VOLUME PRUNE #############"
-          docker system prune -f || { echo "Failed to prune Docker system!"; }
-          docker volume prune -f || { echo "Failed to prune Docker volumes!"; }
+            echo "############# DOCKER SYSTEM AND VOLUME PRUNE #############"
+            docker system prune -f || { echo "Failed to prune Docker system!"; }
+            docker volume prune -f || { echo "Failed to prune Docker volumes!"; }
 
-          echo "############# DOCKER-COMPOSE UP #############"
-          docker-compose -f docker-compose_prod.yml up -d --build --remove-orphans || { echo "Failed to build and start Docker Compose! Exiting."; exit 1; }
+            echo "############# DOCKER-COMPOSE UP #############"
+            docker-compose -f docker-compose_prod.yml up -d --build --remove-orphans || { echo "Failed to build and start Docker Compose! Exiting."; exit 1; }
